### ISSUE TITLE
Find duplicated registers.

### ISSUE THREAD

**Issue by AndresMorelos** [FlavioAandres/Lambdas-WP#20]
With the implementation of PSE parser and Bancolombia one, some PSE and Bancolombia data are making reference to the same payment. we need to find these duplicate payments and just select one to show.

**Comment by FlavioAPareja** [comment]
Hey butt... if bancolombia and pse has the same payment amount and the same description we could take one of them... but in the meantime we can enable the button "delete" in te pre-payment and in that way reject manually one of them

**Comment by AndresMorelos** [comment]
For sure, I will enable the `delete` button on the UI
