### ISSUE TITLE
[Question]: Is good if we implement serverless-layers?

### ISSUE THREAD

**Issue by AndresMorelos** [FlavioAandres/Lambdas-WP#30]
Hey @FlavioAandres,  I just read about the serverless-layers plugin (https://github.com/agutoli/serverless-layers) do you think that is a good idea to implement it? 

If all work as the developers says on the readme this will decrease our current size of 22.9MB for the functions packages.

**Comment by FlavioAandres** [comment]
Hey really we're already using layers, since we added the chromium to the scrapper 😅

its ok for me

**Comment by AndresMorelos** [comment]
@FlavioAandres Ok thank you.
