### ISSUE TITLE
Everything is broken with the last release v1.0.0

### ISSUE THREAD

**Issue by FlavioAandres** [FlavioAandres/Lambdas-WP#31]
With the last changues i got several errors trying to at least run the frontend dev environement: 

My steps: 

1.` cd client/ && npm i` here it installed amplify/react and another new packages
2. `npm start`
3.  it throws an error trying to import `/aws-exports.json`. 
4. I tried to create that json file with no fields and it works but, the authentication didn't work.
5.  Using amplify console i tried with `amplify init, amplify push`  and all resposes to me:  `Could not initialize 'dev': Access Denied`

:) 

@AndresMorelos could you help me here? 😄

**Comment by AndresMorelos** [comment]
@FlavioAandres Try to follow the next steps:

1. `cd client/ && npm i`
2. `amplify pull`
3. Follow the amplify CLI steps (let me know if you are not able to retrieve the information)
4. `amplify push`

**Comment by AndresMorelos** [comment]
@FlavioAandres Was all good?

**Comment by AndresMorelos** [comment]
@FlavioAandres I will close this issue as I did not get an answer, if you still have this issue please reopen it
