### ISSUE TITLE
DataCredito login change, now send a code by email

### ISSUE THREAD

**Issue by AndresMorelos** [FlavioAandres/Lambdas-WP#43]
DataCredito app now sends a code by email to ensure the user login; we need to look for a bypass via API request or scrapper.

The bypass via API request will be the priority.

**Comment by FlavioAandres** [comment]
The problem is only through the login? I mean, if we can break the login the backend allow us receive all the PRO information?

**Comment by AndresMorelos** [comment]
@FlavioAandres Some days after this issue was opened, they change thier backend to verify if there is any payment from the user. :(

**Comment by FlavioAandres** [comment]
I think we can close this until we know a better way to implement data credito again 😅
