### ISSUE TITLE
📦: integrate incomes  with frontend

### ISSUE THREAD

**Issue by FlavioAandres** [FlavioAandres/Lambdas-WP#6]

**Comment by FlavioAPareja** [comment]
@AndresMorelos do you have in mind any way to show this?

**Comment by AndresMorelos** [comment]
@FlavioAPareja @FlavioAandres The expenses are already integrated with the frontend, we need to integrate the incomes, so I will change the title of the issue for that.

I was thinking on show at the home page the incomes like the expenses and on the graph page show a comparative about the incomes and expenses, something like:

1. % of the use of our incomes in payments, or by each category.
2. Expenses rate, I mean the number of days that we took to spent a percentage of our incomes.
3. Expenses thresholds by each category, and maybe integrate a WhatsApp alert with this feature.

Let me know if you have any comment or advice.
