### ISSUE TITLE
📦: New dashbord as homepage with brief sumary of your stats

### ISSUE THREAD

**Issue by FlavioAandres** [FlavioAandres/Lambdas-WP#7]

**Comment by FlavioAPareja** [comment]
@AndresMorelos if you have any new proposal for this dashboard please let it here, otherwise, this is done jaja i did this in another pr but i did not attach it

**Comment by AndresMorelos** [comment]
@FlavioAandres I will close this Issue then; I was thinking on change the client project structure for a better readable one, but that can be a new issue.
